### ISSUE TITLE
undefined method `signrawtransaction`

### ISSUE THREAD

**Issue by JunOkumura** [haw/openassets-ruby#25]
## English
Bitcoin rpc command `signrawtransaction` is deprecated at Bitcoin Core v0.17.0.
That was removed at Bitcoin Core v0.18.0.

This library is not support over v0.18.0.

Can you fix this problem?

Code [here](https://github.com/haw/openassets-ruby/blob/master/lib/openassets/provider/bitcoin_core_provider.rb#L53)
define [here](https://github.com/haw/openassets-ruby/blob/master/lib/openassets/provider/bitcoin_core_provider.rb#L22)

## Japanese
Bitcoin Coreの `signrawtransaction` コマンドが v0.18.0 で完全に削除されました。
このライブラリの実装では `signrawtransaction` に依存したコードがあるため BitcoinCore v0.18.0 以降をサポートできていません。
フィックス可能でしょうか？

**Comment by azuchi** [comment]
9df0f2d now supports`signrawtransactionwithwallet` for 0.18.0. please check it.
